### ISSUE TITLE
Flipping currencies clears the current values

### ISSUE THREAD

**Issue by kolber** [benschwarz/currency.io#2]
We should add a check to only clear the values if either of the new numbers will exceed the space allowed.

**Comment by benschwarz** [comment]
Oh, thats why! I remember it was covering something up.

I was thinking over the weekend, the login form on me.com scales down the values as you type, its surprisingly a good user experience. (Better than the box overflowing/text scrolling)
On Tuesday, 15 March 2011 at 8:21 AM, kolber wrote:
We should add a check to only clear the values if either of the new numbers will exceed the space allowed.

**Comment by kolber** [comment]
Only clear flipped values if they were to overflow
Closed by d737e4b5bdcd650895fc0f2eb77fd55d16dcaa76
