### ISSUE TITLE
Record a new video

### ISSUE THREAD

**Issue by kolber** [benschwarz/currency.io#3]
Using the 'currency.io' domain and faking offline mode.

**Comment by benschwarz** [comment]
I started working on the new video overnight, I just didn't get it edited down right. 
Spend a bit of time using the SimFinger app to fake the phone interface then later realised we're using a cropped video :(

Not sure how we can fake offline mode at all though?

**Comment by kolber** [comment]
I was thinking we could just insert a title screen saying 'Offline mode' and then overlay the aeroplane icon over what we've recorded. Just some simple after effects shiz.
