### ISSUE TITLE
Use HTML5 classList

### ISSUE THREAD

**Issue by benschwarz** [benschwarz/currency.io#5]
If we consider doing this with a polyfill or something, the conditional that we can use is:

`if (!!document.createElement('p').classList)`

**Comment by kolber** [comment]
Can you push this stuff up into a branch so I can test it on iOS3?

**Comment by benschwarz** [comment]
https://github.com/benschwarz/Grip/tree/classList

Don't forget to recompress the scripts… there was an error but I didn't look into it.
